#<% require 'kitchen-sync' %>
---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  flavor_id: <%= ENV['EC2_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:

- name: omnios-151006
  driver_plugin: ec2
  driver_config:
    image_id: ami-35eb835c
    flavor_id: m3.large
    username: root
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  run_list:
  - recipe[ips-omniti]

suites:
  - name: default
    run_list:
      - recipe[ips::test_publisher]
      - recipe[ips::test_repo]
    attributes:
